/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'arrizabalaga' at '5/13/14 12:39 PM' with Gradle 1.11
 *
 * @author arrizabalaga, @date 5/13/14 12:39 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
